[versions]
spring-boot = "4.0.0"
kotlin = "2.2.21"

[plugins]
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }

[libraries]
kotest-assertions-core-jvm = { group = "io.kotest", name = "kotest-assertions-core-jvm", version = "6.0.7" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.10.2" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version = "1.10.2" }
junit-bom = { group = "org.junit", name = "junit-bom", version = "6.0.1" }
r2dbc-postgresql = { group = "org.postgresql", name = "r2dbc-postgresql", version = "1.1.1.RELEASE" }
testcontainersBom = { group = "org.testcontainers", name = "testcontainers-bom", version = "2.0.2" }
testcontainers = { group = "org.testcontainers", name = "testcontainers" }
testcontainers-postgresq = { group = "org.testcontainers", name = "postgresql" }
spring-boot-starter-parent = { group = "org.springframework.boot", name = "spring-boot-starter-parent", version.ref = "spring-boot" }