[plugins]
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version = "2.0.20" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.20" }
kotlin-noarg = { id = "org.jetbrains.kotlin.plugin.noarg", version = "2.0.20" }
spring-boot = { id = "org.springframework.boot", version = "3.3.4" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }

[libraries]
kotest-assertions-core-jvm = { group = "io.kotest", name = "kotest-assertions-core-jvm", version = "5.9.1" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.9.0" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version = "1.9.0" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version = "2.0.16" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.16" }
spring-context = { group = "org.springframework", name = "spring-context", version = "6.1.13" }
spring-web = { group = "org.springframework", name = "spring-web", version = "6.1.13" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version = "3.3.4" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version = "2.17.2" }
r2dbc-postgresql = { group = "org.postgresql", name = "r2dbc-postgresql", version = "1.0.5.RELEASE" }
postgresql = { group = "org.postgresql", name = "postgresql", version = "42.7.4" }
